### ISSUE TITLE
[dev-branch] copy url to keyboard icon looks to be a duplicate of download icon in collections/list.php.

### ISSUE THREAD

**Issue by Atticus29** [Symbiota/Symbiota#1135]
As a bonus, it would be awesome to have the color of the icon itself and the background color informed by variables.css. Hint: this might entail passing a variable to svg code somehow.

![Screen Shot 2024-04-10 at 3 45 49 PM](https://github.com/BioKIC/Symbiota/assets/2775448/8f247411-158c-4a26-9668-1e7292882b36)

**Comment by Atticus29** [comment]
@themerekat can you remind us where you're sourcing these icons from?

**Comment by themerekat** [comment]
Dang I thought I fixed this previously...
You should be able to just replace with this one: https://github.com/BioKIC/Symbiota/blob/Development/images/link.png
