### ISSUE TITLE
[dev-branch] Feedback on portal UI & aesthetics

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1165]

**Comment by themerekat** [comment]
Record Search Form needs to be condensed when not in accessibility mode:
https://dev002.symbiota.org/collections/editor/occurrencetabledisplay.php?displayquery=1&collid=12
![image](https://github.com/BioKIC/Symbiota/assets/16688784/bc5eb719-c0bf-435f-8602-56cc468fb5a2)

- Put "Display Table" buttons on the same line
- Change color of buttons
- Make sure that Copy Link icon is the same color as the text
- Make Entered By, Date Entered, and Date Modified all on the same line (not awkwardly misaligned)
- Sort By, Order By, Record Output on same line
- Unify spacing between lines
- Change icon after "Custom Field 1" to a plus sign instead of pencil with lines

**Comment by themerekat** [comment]
[semi-enhancement]
In search results for occurrencetabledisplay.php:
![image](https://github.com/BioKIC/Symbiota/assets/16688784/49ff4903-800b-4e71-8ecd-26f752f7ea51)
Where there is a highlight, put a button that says "Open Record Search Form" with a caret icon. This re-opens the record search form (which is usually reopened using the magnifying glass icon in the top right).
Remove the magnifying glass icon from the top right.

Similarly, on occurrenceeditor:
Change magnifying glass icon to Open Record Search Form underneath the nagivation:
![image](https://github.com/BioKIC/Symbiota/assets/16688784/769bf773-cd43-4915-b1eb-9ba41894fc3b)
to reopen the record search form

**Comment by themerekat** [comment]
On homepage, default menu should say Search (not Collections)
![image](https://github.com/BioKIC/Symbiota/assets/16688784/14efd615-3895-4d0d-a040-b4a3a3100ea9)

And take you straight to /collections/search/index.php , bypassing /collections/index.php

**Comment by themerekat** [comment]
In /collections/search/index.php, increase size of default label font by 2 sizes-ish
Also of buttons
![image](https://github.com/BioKIC/Symbiota/assets/16688784/2815a865-caa1-4e03-bd30-350648abf449)

**Comment by themerekat** [comment]
Is it possible to change /collections/search/index.php to have smaller margins by default? I.e., the search takes up more of the page?

**Comment by themerekat** [comment]
Move "Reset" button to underneath "Criteria" and change button styling to be less wide and different color
![image](https://github.com/BioKIC/Symbiota/assets/16688784/35fa371b-3d74-4adb-a8fb-bcb55ea5c5e8)

OR just change to a different color (grey versus the main button color)

**Comment by themerekat** [comment]
Default /collections/search/index.php to all sections expanded

**Comment by themerekat** [comment]
In /collections/search/index.php, make sure ALL collections are selected be default: 
![image](https://github.com/BioKIC/Symbiota/assets/16688784/2f40ec40-5efc-43d8-8009-863409dec6ac)

**Comment by themerekat** [comment]
In /collections/list.php
![image](https://github.com/BioKIC/Symbiota/assets/16688784/f9cf2486-cff7-43f8-bdeb-b9a0ea2b3a23)
Make the tabs look more like tabs (i.e., the highlighted tab is white instead of dark grey) and remove the dark grey background to all of the tabs.
Same for: /collections/individual/index.php, /collections/map/index.php and ANY other page that has multiple tabs

This is what the old one looks like, and it should be clear like this (but remove the gray background)
![image](https://github.com/BioKIC/Symbiota/assets/16688784/abe915d0-556b-4c40-822f-334ff8a930da)

**Comment by themerekat** [comment]
https://dev002.symbiota.org/collections/misc/collprofiles.php?collid=12&emode=1
Make box header fonts the same as all the other fonts
![image](https://github.com/BioKIC/Symbiota/assets/16688784/5262bc46-81bd-4358-8ddf-1937ab04c703)

**Comment by themerekat** [comment]
When you conduct a quick search on collprofiles.php, clicking the Edit button takes you to a wonky version of the record search form:
![image](https://github.com/BioKIC/Symbiota/assets/16688784/2badfa57-2d1c-4ebf-b1dc-c2e1d54ee6ae)

**Comment by themerekat** [comment]
Can we have this default to occurrence management as the left tab instead of species checklist. 
![image](https://github.com/BioKIC/Symbiota/assets/16688784/5ec31566-8ef8-47c5-af85-91cd0b339035)

**Comment by jennyost** [comment]
1 - "welcome Jenn" is higher than the right buttons.  Also each of these elements is different.  Maybe there is no “welcome Jenn” and instead is says “Jenn’s Profile” 

![Screenshot 2024-04-23 at 10 23 08 AM](https://github.com/BioKIC/Symbiota/assets/16688825/93914a5b-210c-43e6-a7e6-9b2e7ce778d7)

**Comment by jennyost** [comment]
Here's 

> Record Search Form needs to be condensed when not in accessibility mode: https://dev002.symbiota.org/collections/editor/occurrencetabledisplay.php?displayquery=1&collid=12 ![image](https://private-user-images.githubusercontent.com/16688784/324893075-bc5eb719-c0bf-435f-8602-56cc468fb5a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTI0NTIsIm5iZiI6MTcxMzg5MjE1MiwicGF0aCI6Ii8xNjY4ODc4NC8zMjQ4OTMwNzUtYmM1ZWI3MTktYzBiZi00MzVmLTg2MDItNTZjYzQ2OGZiNWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE3MDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiN2JlNDQwOWM1MjQxY2E1ZTc4ZjQzMDhiMGM0MTRiZGRlN2NmNzMyNDk0ZDBlOGQ1YmZhNjlkYjYwNjMyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V8Mvm3DgJeQAX-dNKPn7clv95ETQEhoKEQEBo5dnw08)
> 
> * Put "Display Table" buttons on the same line
> * Change color of buttons
> * Make sure that Copy Link icon is the same color as the text
> * Make Entered By, Date Entered, and Date Modified all on the same line (not awkwardly misaligned)
> * Sort By, Order By, Record Output on same line
> * Unify spacing between lines
> * Change icon after "Custom Field 1" to a plus sign instead of pencil with lines

Here's an example of a better version: 
![Screenshot 2024-04-23 at 10 42 09 AM](https://github.com/BioKIC/Symbiota/assets/16688825/e7d64996-8fec-4045-8bc8-4189dbee324b)

**Comment by themerekat** [comment]
When viewing the Taxonomic Status tab, the parent taxon isn't italicized (necessary for Genus and Species)
![image](https://github.com/BioKIC/Symbiota/assets/16688784/92c70d3a-f785-4efc-acaa-e3d2c2ac7f62)
View at: https://dev002.symbiota.org/taxa/taxonomy/taxoneditor.php?tid=11390

**Comment by themerekat** [comment]
On this page: https://dev002.symbiota.org/collections/misc/collprofiles.php
if no specific collid is provided, you get a list of all the collections, but the quick search box still shows up. I think this should be removed
![image](https://github.com/BioKIC/Symbiota/assets/16688784/a484cb52-4ea0-45fc-abb8-5e207b829d8d)

**Comment by themerekat** [comment]
In other portals, the "Verify Protections" on this page (https://dev002.symbiota.org/collections/misc/protectedspecies.php) is a button
![image](https://github.com/BioKIC/Symbiota/assets/16688784/62774476-343f-4a52-9adb-0f2bfae57f34)
Is there a reason it was un-buttoned here?

**Comment by themerekat** [comment]
Add spacing below the Reset button on this page: https://dev002.symbiota.org/ident/key.php?clid=135&taxon=All+Species
![image](https://github.com/BioKIC/Symbiota/assets/16688784/b079773d-24e9-4de4-a3d8-6ca80f8cdec1)

**Comment by themerekat** [comment]
On this page: https://dev002.symbiota.org/checklists/checklist.php?clid=158&pid=7

Can the green lines end before they hit the "Options" box?
![image](https://github.com/BioKIC/Symbiota/assets/16688784/cb1e4935-a7c6-44a0-9497-3ef6767ab590)

**Comment by themerekat** [comment]
[probably not important enough to handle for 3.1]
Looks like we need to find svg versions of these icons:
![image](https://github.com/BioKIC/Symbiota/assets/16688784/3b1873f0-039e-41b6-988f-062c20da970a)
They have white backgrounds.
https://dev002.symbiota.org/checklists/checklist.php?clid=158&pid=7

**Comment by themerekat** [comment]
Unify fonts throughout the site to avoid things like this (headers have different font than text)
![image](https://github.com/BioKIC/Symbiota/assets/16688784/eaca6b0a-a293-4b97-872b-014fa8ae8754)
https://dev002.symbiota.org/checklists/checklistadmin.php?clid=157&pid=7

**Comment by themerekat** [comment]
/portal/sitemap.php
![image](https://github.com/BioKIC/Symbiota/assets/16688784/fe48c34d-bdd0-42d1-8b22-31430df61616)
Problem with commenting out a line

**Comment by themerekat** [comment]
> Is it possible to change /collections/search/index.php to have smaller margins by default? I.e., the search takes up more of the page?

Potentially a base rem size.
Default size is defined in base.css
max-inner-text-width in variables.css

**Comment by themerekat** [comment]
These issues have all been fixed or made into separate issues.
