### ISSUE TITLE
[3.1] Unify fonts throughout the site to avoid things like this (headers have different font than text)

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1186]
Unify fonts throughout the site to avoid things like this (headers have different font than text)
![image](https://github.com/BioKIC/Symbiota/assets/16688784/eaca6b0a-a293-4b97-872b-014fa8ae8754)
https://dev002.symbiota.org/checklists/checklistadmin.php?clid=157&pid=7

_Originally posted by @themerekat in https://github.com/BioKIC/Symbiota/issues/1165#issuecomment-2075386701_

**Comment by themerekat** [comment]
Feel free to delete if this is a duplicate

**Comment by Atticus29** [comment]
Not closing yet, because @MuchQuak 's work [here](https://github.com/BioKIC/Symbiota/tree/global-font-size) is also related to this issue.
