### ISSUE TITLE
[3.1] Change search label font size

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1191]
In /collections/search/index.php, increase size of default label font by 2 sizes-ish
Also of buttons ("Search" and "Reset")
![image](https://github.com/BioKIC/Symbiota/assets/16688784/2815a865-caa1-4e03-bd30-350648abf449)

_Originally posted by @themerekat in https://github.com/BioKIC/Symbiota/issues/1165#issuecomment-2072749307_

**Comment by Atticus29** [comment]
@MuchQuak hint: I think that NEON/now we implements these labels by extracting the text from the `data-label` attribute and adding the text as a content attribute on the css side. I'm personally totally fine if we decide not to do it that way lol, especially if that's the only way to assert font sizes of that content.
