### ISSUE TITLE
[3.1] Change size of maximum inner text

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1192]
Is it possible to change /collections/search/index.php to have smaller margins by default? I.e., the search takes up more of the page?

_Originally posted by @themerekat in https://github.com/BioKIC/Symbiota/issues/1165#issuecomment-2072762590_

**Comment by themerekat** [comment]
don't go over 1920 pixels

**Comment by Atticus29** [comment]
@themerekat just to confirm: we only wanted this for the new search page, right? Not a systemic, site-wide change?

**Comment by themerekat** [comment]
I think changing on this page is sufficient for now
