### ISSUE TITLE
[3.1] Change the color of the Reset button

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1193]
Original comment was to move the reset button. Does not need to be moved. Just change the color to grey, red, or some other non-positive color.

![image](https://github.com/BioKIC/Symbiota/assets/16688784/35fa371b-3d74-4adb-a8fb-bcb55ea5c5e8)

OR just change to a different color (grey versus the main button color)

_Originally posted by @themerekat in https://github.com/BioKIC/Symbiota/issues/1165#issuecomment-2072778854_

**Comment by Atticus29** [comment]
Blocked by [https://github.com/orgs/BioKIC/projects/6/views/10?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=37442788&pane=issue&itemId=61517187](https://github.com/orgs/BioKIC/projects/6/views/10?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=37442788&pane=issue&itemId=61517187)

**Comment by themerekat** [comment]
After further discussion, we decided Reset will be inverted colors, and all delete buttons will be a Danger Color
