### ISSUE TITLE
[3.1] Make default all collections selected

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1194]
In /collections/search/index.php, make sure ALL collections are selected be default: 
![image](https://github.com/BioKIC/Symbiota/assets/16688784/2f40ec40-5efc-43d8-8009-863409dec6ac)

_Originally posted by @themerekat in https://github.com/BioKIC/Symbiota/issues/1165#issuecomment-2072800407_

For portals that have categories, need to select only the collections in that category. But we need to test this in portals that do NOT have categories, too.

**Comment by MuchQuak** [comment]
There is an extra problem arisen from this as the reset button adds the collections back and floods the right column. Idk if I should make that a seperate issue.

![Image](https://github.com/BioKIC/Symbiota/assets/91149982/829b3ad2-906f-428f-9289-0a4799077e6a)

**Comment by themerekat** [comment]
> There is an extra problem arisen from this as the reset button adds the collections back and floods the right column. Idk if I should make that a seperate issue.
> 
> ![Image](https://private-user-images.githubusercontent.com/91149982/329103033-829b3ad2-906f-428f-9289-0a4799077e6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjE2OTMsIm5iZiI6MTcxNTIyMTM5MywicGF0aCI6Ii85MTE0OTk4Mi8zMjkxMDMwMzMtODI5YjNhZDItOTA2Zi00MjhmLTkyODktMGE0Nzk5MDc3ZTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAyMjMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZWU0NmFjNmNiMWJjYzNjYjQ0NzVmOTI5ODQ0OTE4YWNlY2Q1NTkyMTZkYTQxY2Q1MDlhYWFjMzUzMTc2ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJzLCiZsr2cuXd3en7fHHIYQM8mTAm_TWe_Y8rBQBXs)

Hmmmm, in a previous version, if you selected all the collections, it would have a chip that says "All Collections"

**Comment by Atticus29** [comment]
@themerekat I am failing to reproduce this issue. Are there perhaps certain circumstances where it's misbehaving?
If I just visit https://cch2.org/portal/collections/search/index.php right now, it's default selecting all collections and I'm only seeing the "All Collections" chip in the criteria section...

**Comment by themerekat** [comment]
@Atticus29 , I think this was the result of trying to go from the "Collections" page to the search page instead of harvestparams!
