### ISSUE TITLE
[3.1] Toggle between Med Res and High Res doesn't work?

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1240]
![image](https://github.com/BioKIC/Symbiota/assets/16688784/aeb1361b-801b-487b-b4ac-a90fc5481852)

E.g., here: https://dev002.symbiota.org/collections/editor/occurrenceeditor.php?csmode=0&occindex=651&occid=4781094&collid=42

**Comment by GregoryPost** [comment]
I think this is a bad test case.  appears to be working with this record:
https://dev002.symbiota.org/collections/editor/occurrenceeditor.php?csmode=0&occindex=0&occid=163843&collid=12

**Comment by themerekat** [comment]
Ok awesome! I found a similar record with the same problem, but likely also a data problem.
