### ISSUE TITLE
[Post 3.1 - Dev branch] and [usda branch]  add role="main" to <div id="innertext elements

### ISSUE THREAD

**Issue by Atticus29** [Symbiota/Symbiota#1281]
Lisa requested: "All the pages for the main content section need role=”main” for the div class=”content” div."

Actually, <div id="innertext"> is the most natural place for this, because class="content" is used for a lot of elements that are not "main"-type containers.

This needs to be implemented immediately in the usda branch, but IMO can wait until after 3.1 if need be. @themerekat what do you think?

**Comment by themerekat** [comment]
@Atticus29 , since it's not really going to affect front-end users, I agree that it's not critical for 3.1
