### ISSUE TITLE
[3.1] Set accessibilityPref to 0 by default (?) or otherwise fix constant error

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1294]
![image](https://github.com/BioKIC/Symbiota/assets/16688784/13a19d35-3217-48ae-94fa-05f98541d3b3)

**Comment by GregoryPost** [comment]
@themerekat I am not able to reproduce this issue.  Where are you seeing it?

**Comment by themerekat** [comment]
@GregPost-ASU this happens when you have error messaging not turned off, and you have not fiddled with the accessibility preference on your profile yet.
