### ISSUE TITLE
Search form "forgets" selected collections and other parameters (v3.1)

### ISSUE THREAD

**Issue by jbest** [Symbiota/Symbiota#1297]
When starting a new search (e.g. at https://www.cch2.org/portal/collections/search/index.php) and selecting specific collections such as RSA Vascular and entering collector name (e.g. "Carlquist"), the search results work, but when you click on "Collections" or "Search Criteria" in the breadcrumb (below the main menu) the search parameters are not retained. I just tested by clicking on the "Search Collections" in the main menu and some parameters are retained, but it changes to All Collections rather than the previously specified collections.

**Comment by themerekat** [comment]
Hi @jbest , try hitting the "back" button instead of clicking the breadcrumb!

**Comment by jbest** [comment]
@themerekat In previous versions of Symbiota, hitting the back button would reset the selected collections (at least in Firefox) so I didn't even try that. But I did test it just now and on Firefox 125.0.3  for Mac, the back button still resets the selections but Chrome 124.0.6367.202 does not.
