### ISSUE TITLE
[3.1?] Specifying multiple collections in search url does not work in search/index.php

### ISSUE THREAD

**Issue by mickley** [Symbiota/Symbiota#1302]
### Contact Details

james.mickley@oregonstate.edu

### Symbiota portal name

CCH2

### What happened?

Previously, one could include a comma-separated-list of collection IDs to search in the search page url, for example: 
https://cch2.org/portal/collections/harvestparams.php?db=[12,81]

On the new search page, that functionality no longer works, this selects all collections:
https://cch2.org/portal/collections/search/index.php?db=[12,81]

The only possibility is to search one collection by collection ID:
https://cch2.org/portal/collections/search/index.php?db=81

### What operational systems are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

**Comment by GregoryPost** [comment]
Hi @mickley,

I was able to run a query using harvestparams.php and comma separating the collids without brackets.
e.g. https://cch2.org/portal/collections/harvestparams.php?db=70,99

Let me know if this works for you.

**Comment by mickley** [comment]
@GregPost-ASU Yes, it still works on harvestparams.php, but I tried this with and without brackets on the new /search/index.php. Neither worked.

**Comment by mickley** [comment]
Woohoo! Nice work all of you!
