### ISSUE TITLE
[3.1] Issue viewing an occurrence editor record

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1321]
Reported by Sara D:

"When I try to access a specimen record on both the RSA Vascular Plants & Xylarium portals on CCH2, the page looks like this, with the specimen image on the extreme right and blank space covering the screen:

![image](https://github.com/BioKIC/Symbiota/assets/16688784/c7654ce0-12de-424f-8c0d-f0dd6dfbc88a)

To view specimen data I have to scroll all the way down, when the image and data should be side by side:

![image](https://github.com/BioKIC/Symbiota/assets/16688784/6e45606f-aeb5-4c89-b600-7876c30e9c92)

**Comment by themerekat** [comment]
Also reported here: https://github.com/BioKIC/Symbiota/issues/1323

**Comment by GregoryPost** [comment]
This appears to caused by reset.css.  Still investigating.
