### ISSUE TITLE
[3.1] From globe icon on /portal/collections/editor/occurrenceeditor.php, map is not zoomed in to the point of interest + error radius

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1326]
Reported by Sara D:

When I click on the globe icon in the "Locality" box, the first map view I get is just of California.

![image](https://github.com/BioKIC/Symbiota/assets/16688784/34f7dfb3-b0fe-411b-a754-70b8c2772647)

I then have to zoom out to be able to find the georeferenced coordinates. Once I do so and zoom back in on the coordinates, the uncertainty radius does not show up on the map, even though it is listed on the screen.

![image](https://github.com/BioKIC/Symbiota/assets/16688784/37c94cdf-e533-42f5-b5e6-52083a711133)

Previously when you clicked on the globe icon, the map would automatically zoom in to display the georeferenced coordinates and the uncertainty radius would show up as well.

**Comment by themerekat** [comment]
Snap to approx. size of error radius

**Comment by MuchQuak** [comment]
Not sure why this didn't auto close from commit but this is should be closed
