### ISSUE TITLE
[3.1] On mobile, hamburger menu is not fully accessible (cannot scroll all the way to sitemap)

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1361]
![Screenshot_20240523-072339_Chrome](https://github.com/BioKIC/Symbiota/assets/16688784/7cde23f7-1289-4068-8bc6-46153dfa4783)
This is as far down as you can scroll on the hamburger menu.

**Comment by GregoryPost** [comment]
@themerekat - what type of device and what mobile browser were you using?  Are you seeing this on all pages or is this just a bug on the image processing results page?

**Comment by themerekat** [comment]
Android, Chrome, all pages
