### ISSUE TITLE
Autofill for State field not set for beginning/whole word

### ISSUE THREAD

**Issue by MiguelGrande** [Symbiota/Symbiota#1395]
This is a minor thing, but in the past, when I typed, e.g., "Calif" in the State field it would find California; by hitting tab, it would fill in quickly. Now, the pop-down menu loads Baja California and Baja California Sur, so I must scroll down the menu past these to California.  This may be true for other fields. I suggest that autofill work with the beginning text of a list, not embedded text.

**Comment by themerekat** [comment]
I believe this has been addressed in another PR. @MuchQuak , can you confirm?
