### ISSUE TITLE
[3.1] Mapped collections with same georeference can't be distinguished.

### ISSUE THREAD

**Issue by MiguelGrande** [Symbiota/Symbiota#1399]
When mapping a series of collections, if one or more entries have the same lat/long, only one shows up on a map and can be clicked/viewed. In the past, one would get a view of collections with the same georeference appearing as radiating lines ending in circles, the latter individual collections. Can that be done again?

**Comment by themerekat** [comment]
@MuchQuak , this is the spidering feature
