### ISSUE TITLE
[3.1] Changes to leaflet map from occurrence editor (/collections/tools/mappointaid.php)

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1407]
- [ ] When you open the mappointaid, make the hand (not the pointer) the default when there is already a coordinate being passed to it (people don't usually want to place a new point when they're opening up the mappointaid, but they do want to be able to pan around to view the context of the existing point). Make the pointer (i.e., placement of a new marker) default only when there is no pre-existing coordinate.
- [ ] Add ability to adjust error radius by clicking on the edge of the radius and dragging in or out. See functionality in the previous version of the mappointaid. You should be able to adjust the error radius without having to type it in manually.

**Comment by MuchQuak** [comment]
First Issue should be easy enough to implement. I will take a crack at the second one but I am am not sure there will be a nice solution.
