### ISSUE TITLE
[3.1] Trouble merging duplicates

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1451]
Getting this error:
![image](https://github.com/BioKIC/Symbiota/assets/16688784/2f52db5b-ea79-4706-b2ef-c70e362ee6bf)

**Comment by themerekat** [comment]
Problem appears to be line 1592 in OccurrenceEditorManager. Need to allow for a case when the record you would like to merge over has no determinations.

**Comment by MuchQuak** [comment]
Hmm yeah this is odd thanks for the specific feedback I will get right on it
