### ISSUE TITLE
[3.1] In checklists, scientific names should be bold

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1490]
Right now, the name is not bold and the authorship is bold:
![image](https://github.com/BioKIC/Symbiota/assets/16688784/658adf0e-95b6-41aa-930f-4ef629378539)

The scientific name should be bold, and the authorship NOT bold.
(or if that's really annoying to do, just make everything not bold, like it used to be)

**Comment by ksorellana** [comment]
If it helps, the autorship is also bold in the previous version.
![image](https://github.com/BioKIC/Symbiota/assets/69399374/2399b33c-076b-4f64-af3d-97cf65be9921)
