### ISSUE TITLE
[3.1] Rapid search is showing up at the top of collprofiles, rather than to the right

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1496]
![image](https://github.com/BioKIC/Symbiota/assets/16688784/2e51bcb6-1139-4b80-99d7-83f60f60bb41)
https://biodiversidad.gt/dev/collections/misc/collprofiles.php?collid=26

**Comment by MuchQuak** [comment]
This Just has to do with screen resolution. It will not appear on the right if there isn't room for it. Breakpoint currently is at 1880px wide screens. I could try to get it lower but it is a pretty tight fit as is

**Comment by themerekat** [comment]
@MuchQuak , hm, I'm on a generic laptop screen and it's showing up at the top.
