### ISSUE TITLE
Tabs aren't showing up in list.php in Guatemala portal

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1500]
![image](https://github.com/BioKIC/Symbiota/assets/16688784/5f17fa7f-3f87-4c8c-8fb2-ae069c4f79e0)

**Comment by themerekat** [comment]
"Also in List Search Results: If I click “Search Criteria” on the top menu, it takes me to the old search form instead of the new one."

**Comment by GregoryPost** [comment]
I was still working on some merge issues.  Should be fixed now.
