### ISSUE TITLE
[3.1] Create specific header text styling variable so that the header text is not affected by universal text size increase

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1505]
The header font in CCH2 is too big, now. Header files are likely to be highly customized, so font size changes to the site should probably not affect them.
See this Slack exchange: https://symbiota-support.slack.com/archives/C032ZCUK7EX/p1720808364931799

**Comment by MuchQuak** [comment]
Do we want this variable or do we want to just fix their css because they are likely using large rem values

**Comment by themerekat** [comment]
I think we do want this variable. The header looks fine now because I changed their css, but in the future, I think people will likely not want to change the header when they increase the site font size.

**Comment by MuchQuak** [comment]
So there is a variable to control this but it is overwritten by custom css in the cch2 header and I will need to get on biokic5 to fix this

**Comment by MuchQuak** [comment]
Greg and I fixed this on cch2 production
