### ISSUE TITLE
[3.1] Pages that still need increased font size

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1506]
- [x] /profile/viewprofile.php
- [x] /profile/userprofile.php
- [x] /profile/occurrencemenu.php
- [x] /checklists/checklistadmin.php
- [x] files under /collection/loans/
- [x] files under /collections/specprocessor/

**Comment by ljwalker** [comment]
- [x] /taxa/taxonomy/taxoneditor.php
- [x] /collections/individual/index.php
- [x] /collections/misc/collmetadata.php
