### ISSUE TITLE
[audio] Change the "image root" in symbini to "media root" and all references

### ISSUE THREAD

**Issue by MuchQuak** [Symbiota/Symbiota#1554]
Reason Apart of the audio file work

 Generalize image root to media root
- Change References to image root to media root
- Allow back compatibility for old symbini files by assign image root to media root if media root is undefined

**Comment by themerekat** [comment]
On this record: https://dev004.symbiota.org/portal/collections/editor/occurrenceeditor.php?csmode=0&occindex=0&occid=354466&collid=8

Click Images tab.

I try to change the Photographer to someone from the dropdown menu.

I get this:
![image](https://github.com/user-attachments/assets/a838af01-5625-46c7-b0fc-699ba86632ec)

In fact, I get that same problem whenever I try to make an edit to a record in the Images tab (change the image URL, add image tags, etc.)

**Comment by themerekat** [comment]
Things that work right now:
- [x] Add new image
- [x] Search for records that have images
- [x] Image search by collection
- [x] Image search by scientific name
- [x] Save image tags
- [x] Save edits to image URLs
- [x] Link image to new occurrence
- [x] Using the Image Search to search on image tags
- [x] Batch tagging images

**Comment by themerekat** [comment]
Search by records with images seems to work

**Comment by themerekat** [comment]
Changes to Photographer (photographeruid) and photographer text field do not save
![image](https://github.com/user-attachments/assets/145ac354-93b4-496b-bd3b-21fcc7b4cc41)

Saves to the URL fields _do_ work

**Comment by themerekat** [comment]
Clicking "Dissociate Image" button results in the doom screen
![image](https://github.com/user-attachments/assets/8617b89d-9437-4275-a5b4-2788d35f8f13)

**Comment by themerekat** [comment]
Cannot add an image to the Glossary
![image](https://github.com/user-attachments/assets/f26155e4-f558-4e1f-b52e-10457dbec2b8)

https://dev004.symbiota.org/portal/glossary/termdetails.php#termimagediv
(but not sure if this is just a config issue)

**Comment by themerekat** [comment]
By default, you can only see mp3 and png files. Most files will be jpgs, but there are a lot of other formats we want to support. ![image](https://github.com/user-attachments/assets/c648ede3-e4d5-40b9-a55e-3a5fdcb541df)

**Comment by themerekat** [comment]
Adding, playing, and removing audio files works!

**Comment by themerekat** [comment]
I uploaded a PDF and got this message:
![image](https://github.com/user-attachments/assets/bcc3709c-050a-4a50-8dc5-e3b00f060f64)

but obviously nothing shows up. There is no "image" for this added media. We should probably add error handling to this and not allow PDFs.

**Comment by themerekat** [comment]
I don't think we need to import a link to the audio recording to all three of these fields. It can probably just go into one: 
![image](https://github.com/user-attachments/assets/e003c11d-dd07-4b4c-8732-8c4e31d58f23)

**Comment by themerekat** [comment]
Need to change the verbiage of the highlighted items to "resource".

But the last one is in the imagetag table, so probably a schema change.

![image](https://github.com/user-attachments/assets/98316468-ec9c-4557-869d-b3bc6eeb4326)

**Comment by themerekat** [comment]
Also these ones:
![image](https://github.com/user-attachments/assets/9ddaf981-99f9-4ccb-8947-cb8d9daa34bc)

**Comment by themerekat** [comment]
Adding, playing, and deleting audio files still works!

**Comment by themerekat** [comment]
Still need to change the image search interface, but I'm sure that's on the list:
![image](https://github.com/user-attachments/assets/7a16894a-5687-4dba-8ccd-0be86946c6d8)
/portal/imagelib/search.php

**Comment by themerekat** [comment]
Image search currently shows "thumbnails" even of audio files
![image](https://github.com/user-attachments/assets/b2a20a30-86c7-46e7-a491-37e25ed27079)

**Comment by themerekat** [comment]
Need better handling of "thumbnails" in the public display page. Audio player should be queued up here so that someone could play the file from here
![image](https://github.com/user-attachments/assets/248f4dde-44b3-460a-80b8-d4adf97237a8)

**Comment by themerekat** [comment]
Show audio icon on search results when a record has an audio file
![image](https://github.com/user-attachments/assets/32669698-bc19-4ab0-bb3f-238d57955c7b)
