### ISSUE TITLE
[3.1] Geographic lookup list on Occurrence Editor not displaying in Bryophyte Portal 

### ISSUE THREAD

**Issue by ljwalker** [Symbiota/Symbiota#1631]
Following the Bryophyte Portal's code upgrade, the geographic lookup list on the Occurrence Editor is no longer displaying when tested on Chrome, Safari, and Brave. However, this feature _is_ working in CCH2 and Lichen Portal.

User reports that they are using "Win11, chrome, updated to newest version. And also win10 and chrome".

Screenshots provided by user:
![Clipboard_NoCountyPicklist](https://github.com/user-attachments/assets/9b1a2a1e-fdd6-4e01-9f36-84352b96299c)
![Clipboard_NoStatePicklist](https://github.com/user-attachments/assets/0a46fe7d-2e32-47d0-af01-a8f1fa63764e)

Relates to [osTicket #0005178](https://help.symbiota.org/scp/tickets.php?id=4228).

**Comment by GregoryPost** [comment]
Geo thesaurus needed to be transferred. Working now.
