### ISSUE TITLE
In Taxonprofile.php(476) and (487): Uncaught Error: Call to a member function fetch_object()

### ISSUE THREAD

**Issue by andresortizcomar** [Symbiota/Symbiota#165]
The function setLinkArr() make a select from the table taxalinks, but that table is empty. Thanks for the help.

**Comment by themerekat** [comment]
Hi @andresortizcomar , which portal are you experiencing this error in? Were you trying to add a taxon to the taxon table?

**Comment by themerekat** [comment]
@andresortizcomar , can you give me more information about this problem as per my questions above?
