### ISSUE TITLE
[audio] Handle audio files stored elsewhere and linked to Media tab

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1673]
Not sure if it is possible to play audio files linked from external sources, but if it is, we should. If it is not possible, I think we shouldn't show the audio player at all, and instead just have a link out to the URL.

**Comment by MuchQuak** [comment]
There is certain formats that will not work out of the box that could be stored externally. Aside from that though if you can access it via a link that is directly to the resource it will play.
