### ISSUE TITLE
[audio] Add audio symbol to records that have audio in Occurrence Table Display

### ISSUE THREAD

**Issue by MuchQuak** [Symbiota/Symbiota#1698]
![Image](https://github.com/BioKIC/Symbiota/assets/16688784/df6d7162-c94e-406e-bc77-b91b4e917259)

**Comment by MuchQuak** [comment]
Is this a 3.1 portal? I currently don't see any logic for images. Maybe it got removed by accident

**Comment by themerekat** [comment]
Oh, I think I meant listtabledisplay, e.g., https://cch2.org/portal/collections/listtabledisplay.php
