### ISSUE TITLE
[audio] Adjustments to audio support features

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1711]

**Comment by themerekat** [comment]
This page still uses "photographer" and "images" https://dev004.symbiota.org/portal/imagelib/contributors.php

**Comment by themerekat** [comment]
On a public display page, e.g., https://dev004.symbiota.org/portal/collections/individual/index.php?occid=354466&clid=0
![image](https://github.com/user-attachments/assets/20ce0724-848e-40f5-ba7a-0b7982f10dd6)

Can just change "Open Large Multimedia File" to "Open Large File", etc.

**Comment by themerekat** [comment]
Large URL is still "Large Image URL". I think it should be "Large File URL"
![image](https://github.com/user-attachments/assets/7b08ed44-befe-405d-b145-1a442bcd0bb4)
https://dev004.symbiota.org/portal/collections/editor/occurrenceeditor.php?occid=354466

**Comment by themerekat** [comment]
In the media search, one of the records isn't showing the audio file icon: https://dev004.symbiota.org/portal/imagelib/search.php?taxontype=2&usethes=1&tagExistance=1
![image](https://github.com/user-attachments/assets/7aeaaacc-e0d9-4727-b141-73a988e4d28d)

Any idea why?

**Comment by themerekat** [comment]
On side panel of map search, should probably say "limit to specimens with media only"
![image](https://github.com/user-attachments/assets/87abadda-b5d2-42e8-893e-3a087f87f8a5)
https://dev004.symbiota.org/portal/collections/map/index.php

Or better yet, add the new tags from the specimen search:
![image](https://github.com/user-attachments/assets/5e917f3e-90b9-4d56-b54c-38e6422723d0)

**Comment by themerekat** [comment]
In the Exporter tool, change "Image" to "Multimedia"
![image](https://github.com/user-attachments/assets/367bd2a3-782b-4c6b-b423-b960f1516b34)
https://dev004.symbiota.org/portal/collections/specprocessor/index.php?collid=8

**Comment by themerekat** [comment]
In regular download panel, change Image to Multimedia
![image](https://github.com/user-attachments/assets/ef083a89-261a-44a9-bc03-42ea903124c1)
https://dev004.symbiota.org/portal/collections/download/index.php

**Comment by themerekat** [comment]
Things that work:
- [x] uploading a new audio file
- [x] searching for audio files in the "media search"
- [x] downloading dwc-as that include sound files
- [x] deleting audio files
- [x] changing metadata associated with sound files

**Comment by themerekat** [comment]
On a search result, if a record has an audio file, I think the audio icon should be visible on that result in the list view.
![image](https://github.com/user-attachments/assets/d6456bbb-9021-44fb-8990-5f6e2353fa1b)
https://dev004.symbiota.org/portal/collections/list.php

**Comment by MuchQuak** [comment]
> Large URL is still "Large Image URL". I think it should be "Large File URL" ![image](https://private-user-images.githubusercontent.com/16688784/366627891-7b08ed44-befe-405d-b145-1a442bcd0bb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjQyMjEsIm5iZiI6MTcyNjE2MzkyMSwicGF0aCI6Ii8xNjY4ODc4NC8zNjY2Mjc4OTEtN2IwOGVkNDQtYmVmZS00MDVkLWIxNDUtMWE0NDJiY2QwYmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3NTg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZTYwNzE4NGU1ZTYwODAzZjE3ODk2NDQ5YmIzOWU4M2Y1ZGZjMmE4NjVhZjlmMzUzZjUyOWE2YzMyMjEzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nUahxfiRowBOeY5KwNVoloS9vtleTPMMU0JYTRvmINA) https://dev004.symbiota.org/portal/collections/editor/occurrenceeditor.php?occid=354466

There is only an every a large image file there is no large audio would this change still be needed?

**Comment by MuchQuak** [comment]
> On side panel of map search, should probably say "limit to specimens with media only" ![image](https://private-user-images.githubusercontent.com/16688784/366629155-87abadda-b5d2-42e8-893e-3a087f87f8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjQyMjEsIm5iZiI6MTcyNjE2MzkyMSwicGF0aCI6Ii8xNjY4ODc4NC8zNjY2MjkxNTUtODdhYmFkZGEtYjVkMi00MmU4LTg5M2UtM2EwODdmODdmOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3NTg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjY2Q5ZTg4NzcxZmNiNmY2MzVhNThhNDU2NTJmYzY4ZWVkMmVmNzUwMTc5OGJkOWRmN2VlYmZlNGEzOTI0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wZsaQaxVulUUDpcwrQV8lGadP-hdPN68w8YxGXzwKsk) https://dev004.symbiota.org/portal/collections/map/index.php
> 
> Or better yet, add the new tags from the specimen search: ![image](https://private-user-images.githubusercontent.com/16688784/366629316-5e917f3e-90b9-4d56-b54c-38e6422723d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjQyMjEsIm5iZiI6MTcyNjE2MzkyMSwicGF0aCI6Ii8xNjY4ODc4NC8zNjY2MjkzMTYtNWU5MTdmM2UtOTBiOS00ZDU2LWI1NGMtMzhlNjQyMjcyM2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3NTg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTcyODljMzJkMDJhYmViYzE1NDBjM2U2ODQwZGYyMDNlYmZjYzcxMzg0NGExODM1YjFjOGRlOTdjYTU3YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0FUSLL2Ieud99sI7efbvzu4QPRtm8znBG1IiRtxE3tQ)

Thanks for catching that one I missed it!

**Comment by themerekat** [comment]
> > Large URL is still "Large Image URL". I think it should be "Large File URL" ![image](https://private-user-images.githubusercontent.com/16688784/366627891-7b08ed44-befe-405d-b145-1a442bcd0bb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjQyMjEsIm5iZiI6MTcyNjE2MzkyMSwicGF0aCI6Ii8xNjY4ODc4NC8zNjY2Mjc4OTEtN2IwOGVkNDQtYmVmZS00MDVkLWIxNDUtMWE0NDJiY2QwYmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3NTg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZTYwNzE4NGU1ZTYwODAzZjE3ODk2NDQ5YmIzOWU4M2Y1ZGZjMmE4NjVhZjlmMzUzZjUyOWE2YzMyMjEzZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nUahxfiRowBOeY5KwNVoloS9vtleTPMMU0JYTRvmINA) https://dev004.symbiota.org/portal/collections/editor/occurrenceeditor.php?occid=354466
> 
> There is only an every a large image file there is no large audio would this change still be needed?

When there's an audio file, isn't it automatically stored in the "Large" field? Maybe it needs to be renamed to something like "maximum size" or "original size"? I'm not really sure...

**Comment by MuchQuak** [comment]
> In the media search, one of the records isn't showing the audio file icon: https://dev004.symbiota.org/portal/imagelib/search.php?taxontype=2&usethes=1&tagExistance=1 ![image](https://private-user-images.githubusercontent.com/16688784/366628574-7aeaaacc-e0d9-4727-b141-73a988e4d28d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTEyNDEsIm5iZiI6MTcyNjE5MDk0MSwicGF0aCI6Ii8xNjY4ODc4NC8zNjY2Mjg1NzQtN2FlYWFhY2MtZTBkOS00NzI3LWIxNDEtNzNhOTg4ZTRkMjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDAxMjkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NmY3Nzk3NDgwMmJlZWYzYWQzMzk5MTQ5NzQzMmEyMzlhMDQwNTU0MmE3NDhjYWM5NmUxNWM2NmJjMzAyMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7Xwr1jrcZNH2RXn7cXzJFxEb8KstZiztAjbgr3vXK4Y)
> 
> Any idea why?

I think this is just and old upload that hand thumbnail url as an mp3. The speaker image is only used if there isn't a thumbnail because you could add one for audio if you wanted

**Comment by ljwalker** [comment]
https://dev004.symbiota.org/portal/imagelib/index.php 
![Screenshot 2024-09-13 at 12 25 03 PM](https://github.com/user-attachments/assets/c33fa8e7-76d0-4ccf-ae3d-ecf045360f09)

**Comment by ljwalker** [comment]
https://dev004.symbiota.org/portal/imagelib/index.php
<img width="1005" alt="Screenshot 2024-09-13 at 12 32 20 PM" src="https://github.com/user-attachments/assets/67256bfc-8419-4691-9638-ccf3bb0717d3">

**Comment by ljwalker** [comment]
https://dev004.symbiota.org/portal/sitemap.php

@themerekat Does it make sense to update this section of the Sitemap, or keep as-is? 

Suggested edits:
- Change "Images" header to "Multimedia"
- Will eventually need to update URL to "Image Submission" once new docs are available
- Selective text edits:
> See the Symbiota documentation on [Image Submission](https://biokic.github.io/symbiota-docs/editor/images/) for an overview of how images are managed within a Symbiota data portal. Field images without detailed locality information can be uploaded using the Taxon Species Profile page. Specimen images **[[and other media]]** are loaded through the ~~Specimen Editing page~~ **[[Occurrence Editor]]** or through a batch upload process established by a portal manager. Image Observations (Image Vouchers) with detailed locality information can be uploaded using the link below. Note that you will need the necessary permission assignments to use this feature.

<img width="1021" alt="Screenshot 2024-09-13 at 12 37 30 PM" src="https://github.com/user-attachments/assets/46efa502-9d65-47ac-93e6-17c9713c317e">

**Comment by ljwalker** [comment]
https://dev004.symbiota.org/portal/taxa/profile/tpeditor.php?tid=33468 > Multimedia tab:
<img width="924" alt="Screenshot 2024-09-13 at 1 00 49 PM" src="https://github.com/user-attachments/assets/32adfa8a-9bd6-4887-a031-7ce2e26ac377">

**Comment by ljwalker** [comment]
https://dev004.symbiota.org/portal/collections/misc/collprofiles.php?collid=8
<img width="583" alt="Screenshot 2024-09-13 at 1 11 09 PM" src="https://github.com/user-attachments/assets/0f887404-ed94-490c-9309-488d999124f3">
<img width="1055" alt="Screenshot 2024-09-13 at 1 09 28 PM" src="https://github.com/user-attachments/assets/e24a9b1b-1e5c-4b75-bc4a-eab13200e588">

**Comment by ljwalker** [comment]
https://dev004.symbiota.org/portal/collections/specprocessor/index.php?collid=8
@themerekat Will ingestion of non-image multimedia files potentially integrate with the Globus workflow? If yes, suggested changes:
<img width="1069" alt="Screenshot 2024-09-13 at 1 15 45 PM" src="https://github.com/user-attachments/assets/7ffeb15b-12ed-45f2-a522-54effb5ed181">

**Comment by themerekat** [comment]
> https://dev004.symbiota.org/portal/collections/specprocessor/index.php?collid=8 @themerekat Will ingestion of non-image multimedia files potentially integrate with the Globus workflow? If yes, suggested changes: <img alt="Screenshot 2024-09-13 at 1 15 45 PM" width="1069" src="https://private-user-images.githubusercontent.com/11181096/367435675-7ffeb15b-12ed-45f2-a522-54effb5ed181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNjY2MjEsIm5iZiI6MTcyNjI2NjMyMSwicGF0aCI6Ii8xMTE4MTA5Ni8zNjc0MzU2NzUtN2ZmZWIxNWItMTJlZC00NWYyLWE1MjItNTRlZmZiNWVkMTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDIyMjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YWE3OWMyYTYwMDg3NWE5YzE4NzUyNDQ0YjBlYmM5Mzg1MTBlZDEzYjUxMzMyZDE1YmEwYjBkYjMyYjJmYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qowUBZ_TylCDoQcDzaUt3YReNoLD8LHZjenWtT4Ei-8">

I think the same workflow could be used. I would have to check with Greg.

**Comment by ljwalker** [comment]
From /portal/collections/download/index.php: 
![Screenshot 2024-09-15 at 9 12 42 AM](https://github.com/user-attachments/assets/ae638242-0fb1-4fee-a256-89388fb8b904)

**Comment by MuchQuak** [comment]
Thanks for all the catches Lindsay, I should be able to get them up quickly

**Comment by MuchQuak** [comment]
> https://dev004.symbiota.org/portal/imagelib/index.php ![Screenshot 2024-09-13 at 12 25 03 PM](https://private-user-images.githubusercontent.com/11181096/367424142-c33fa8e7-76d0-4ccf-ae3d-ecf045360f09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MjUxMzgsIm5iZiI6MTcyNjUyNDgzOCwicGF0aCI6Ii8xMTE4MTA5Ni8zNjc0MjQxNDItYzMzZmE4ZTctNzZkMC00Y2NmLWFlM2QtZWNmMDQ1MzYwZjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDIyMTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YjA0Y2MwYWIxYjM5YjdmYmI1MmE3N2FiNWIwYTg3YmViYzJjMWY0YmQxMzE2ZjM5MmFmNmJjYWMzMjM0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nIr9FuHldDB8EKYMvYITjdAlTy109isupr_1BotIN3I)

Didn't even know this page existed XD

**Comment by aidan-houlihan** [comment]
Occurrence editor Action Status messages following media upload/deletion show image upload/deletion respectively 

<img width="891" alt="action_status" src="https://github.com/user-attachments/assets/f460d5e3-61bc-4730-a416-e742e1398577">

<img width="884" alt="actions_status_delete" src="https://github.com/user-attachments/assets/9404b1ca-ccf0-4fcd-9183-bfac596adf85">

**Comment by aidan-houlihan** [comment]
https://dev004.symbiota.org/portal/collections/datasets/datapublisher.php?collid=1 

Darwin Core Archive Publishing page: "Image metadata" & "Include Image URLs"
<img width="1086" alt="darwin_core_archive_pub" src="https://github.com/user-attachments/assets/462537ae-5b5a-49dc-b23b-2f62f08d5d11">

**Comment by aidan-houlihan** [comment]
Issue with using the bulk media URL mapping utilities (in Proccessing Toolbox and Extended Data Import). 

Did test uploads via both the Processing Toolbox Image Loader and the Image Field mapper under Extended Data Import but ran into some issues. I was using a single record in a csv file with catalogNumber and resourceURL (attached). For the processing toolbox utility, the process hangs in the Specimen Processor Control Panel with the attached log file. 

For the URL mapper using the Image Field Map option, and the same csv file, the URL is associated with the specimen, but a "thumbnail" and image viewer box are also generated alongside, and the audio player isn't available (but clicking "Open Original File" will open a new tab with the sound clip). See ASUHEC000001 for these results and attached screenshot, as this was the testing record I used. (Ignore the :54 second clip, that was there prior to the test upload)
<img width="1361" alt="Screenshot 2024-09-30 at 11 44 45" src="https://github.com/user-attachments/assets/c0f1e7b6-a160-42ac-8e5d-0bcd57a9aa77">


It's also entirely possible that I have the uploads setup incorrectly, I haven't used them before. I had catalogNumber mapped to catalogNumber, and the resourceURL mapped to either "Large Image URL (required)" for the Proccessing Toolbox Image Loader, and mapped to originalURL for the Extended Data Importer image field mapping.

Log File:
[1_ASU-ASUHEC_2024-09-27.txt](https://github.com/user-attachments/files/17195676/1_ASU-ASUHEC_2024-09-27.txt)
CSV File Used:
[url_upload_test_otte.csv](https://github.com/user-attachments/files/17195668/url_upload_test_otte.csv)

**Comment by themerekat** [comment]
> Issue with using the bulk media URL mapping utilities (in Proccessing Toolbox and Extended Data Import).
> 
> Did test uploads via both the Processing Toolbox Image Loader and the Image Field mapper under Extended Data Import but ran into some issues. I was using a single record in a csv file with catalogNumber and resourceURL (attached). For the processing toolbox utility, the process hangs in the Specimen Processor Control Panel with the attached log file.
> 
> For the URL mapper using the Image Field Map option, and the same csv file, the URL is associated with the specimen, but a "thumbnail" and image viewer box are also generated alongside, and the audio player isn't available (but clicking "Open Original File" will open a new tab with the sound clip). See ASUHEC000001 for these results and attached screenshot, as this was the testing record I used. (Ignore the :54 second clip, that was there prior to the test upload) <img alt="Screenshot 2024-09-30 at 11 44 45" width="1361" src="https://private-user-images.githubusercontent.com/67758412/372222153-c0f1e7b6-a160-42ac-8e5d-0bcd57a9aa77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MjU2MDMsIm5iZiI6MTcyNzcyNTMwMywicGF0aCI6Ii82Nzc1ODQxMi8zNzIyMjIxNTMtYzBmMWU3YjYtYTE2MC00MmFjLThlNWQtMGJjZDU3YTlhYTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDE5NDE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNDFmMDJmYjQ3Y2ExMzZmYjFkMjM1ODExNzNiYjE3NWRjMDhkYTQ1YWVlZmY3Y2U3YzAwZTNlYTViN2U5OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9lq8CLlHlSy1BCjR7Docmx0evTvDP1pM8x2FA4A-PZ0">
> 
> It's also entirely possible that I have the uploads setup incorrectly, I haven't used them before. I had catalogNumber mapped to catalogNumber, and the resourceURL mapped to either "Large Image URL (required)" for the Proccessing Toolbox Image Loader, and mapped to originalURL for the Extended Data Importer image field mapping.
> 
> Log File: [1_ASU-ASUHEC_2024-09-27.txt](https://github.com/user-attachments/files/17195676/1_ASU-ASUHEC_2024-09-27.txt) CSV File Used: [url_upload_test_otte.csv](https://github.com/user-attachments/files/17195668/url_upload_test_otte.csv)

Good points, and thanks for your careful investigation! I don't know if we have worked on using this tool with media records yet.

**Comment by MuchQuak** [comment]
@aidan-houlihan Import fix is up on the development server. There are some plans to deprecate some processing toolbox features so the changes were made to the https://dev004.symbiota.org/portal/collections/admin/importextended.php?collid=1 tool found under collection profile -> Administration Control Panel -> Import/Update Specimen Records -> Extended Data Import.

**Comment by aidan-houlihan** [comment]
@MuchQuak Success on my end! The audio went in just fine and could be played right from the media tab. But when trying to import data to other fields (caption, notes, rights etc. see attached csv of most recent test), the data doesn't appear along with the audio in the media tab, just blank fields. 

Other minor issue is the Action Panel log of the import hangs on "Updating Statistics", and also says "Empty dateIdentified values have been set as " and doesn't finish its thought, but the import still goes through (see attached screenshot). Maybe only an issue since some functionality is deactivated in the dev portal?

Upload Test CSV:
[other_fields_upload_audio_test.csv](https://github.com/user-attachments/files/17262881/other_fields_upload_audio_test.csv)

Action Panel Hang:
<img width="882" alt="Screenshot 2024-10-04 at 15 16 36" src="https://github.com/user-attachments/assets/a419e606-cc12-4b43-8d3e-4ddcc79ab969">

**Comment by MuchQuak** [comment]
> @MuchQuak Success on my end! The audio went in just fine and could be played right from the media tab. But when trying to import data to other fields (caption, notes, rights etc. see attached csv of most recent test), the data doesn't appear along with the audio in the media tab, just blank fields.
> 
> Other minor issue is the Action Panel log of the import hangs on "Updating Statistics", and also says "Empty dateIdentified values have been set as " and doesn't finish its thought, but the import still goes through (see attached screenshot). Maybe only an issue since some functionality is deactivated in the dev portal?
> 
> Upload Test CSV: [other_fields_upload_audio_test.csv](https://github.com/user-attachments/files/17262881/other_fields_upload_audio_test.csv)
> 
> Action Panel Hang: <img alt="Screenshot 2024-10-04 at 15 16 36" width="882" src="https://private-user-images.githubusercontent.com/67758412/373782232-a419e606-cc12-4b43-8d3e-4ddcc79ab969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNzM3MjgsIm5iZiI6MTcyODA3MzQyOCwicGF0aCI6Ii82Nzc1ODQxMi8zNzM3ODIyMzItYTQxOWU2MDYtY2MxMi00YjQzLThkM2UtNGRkY2M3OWFiOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDIwMjM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NGUzMDYwMjM5MDdlNTAzZWFjNWMzNDBiZTIxNjJjYmIxZjY4ZDQ0MDg5YTBhZjZjMzc2NThlZTNhZjJmNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rX5q_Szt6AeColjVANE6rlmUluoVAKAKHalkXy8gi_U">

Okay, I will get those issues checked out thanks for being thorough!

**Comment by MuchQuak** [comment]
@aidan-houlihan I pushed fixes for the above issues let me know if you find anything else.
