### ISSUE TITLE
SSl Option

### ISSUE THREAD

**Issue by Kantoborgy** [Symbiota/Symbiota#1756]
Hello,

New version 3.1

If I click on one of the search results on the map, the link gives an error because it automatically prefaces https and must only be http if I don't have an SSL certificate activated.

edit /../collections/map/rcp/searchcollections.php

old: $host = ($SERVER_HOST === '127.0.0.1' || $SERVER_HOST === 'localhost'? "http://": "https://") . $SERVER_HOST . $CLIENT_ROOT;

new: $host = ($SERVER_HOST === '127.0.0.1' || $SERVER_HOST === 'localhost'? "http://": "http://") . $SERVER_HOST . $CLIENT_ROOT;

This change works. Could it cause errors? 

Thank you in advance

**Comment by MuchQuak** [comment]
Are you running locally or on a server. If its on a server, I would getting certificates to run https otherwise it is a security issue. If running on local then their is a issue with that snippet not allowing more port numbers which I will fix
