### ISSUE TITLE
Update URL on sitemap

### ISSUE THREAD

**Issue by ljwalker** [Symbiota/Symbiota#1769]
In _sitemap.php_:

<img width="1102" alt="Screenshot 2024-10-08 at 9 35 43 AM" src="https://github.com/user-attachments/assets/355688fc-f48f-4cbc-9f1e-7fde3dd7ed19">

The link to "Symbiota Documentation" currently links to a defunct page on symbiota.org. This URL should point to https://biokic.github.io/symbiota-docs/col_obs/ and the wording should be updated.

Old text:
> Visit the Symbiota Documentation for more information on specimen processing capabilities.

Suggested text:
> Visit the [Collector/Observer Guide](https://biokic.github.io/symbiota-docs/col_obs/) to learn more about managing observational records in Symbiota portals.

**Comment by themerekat** [comment]
Looks like the link has already been updated in the master code; it just hasn't been integrated into SEINet (which is still on 3.0). I'm not going to update the link text in case we change the name of the guide in the future.
