### ISSUE TITLE
Add french translation files to taxonomy files

### ISSUE THREAD

**Issue by Atticus29** [Symbiota/Symbiota#1783]
Not sure whether this is an oversight or a low priority or not desired for some reason.

<img width="1552" alt="Screenshot 2024-10-15 at 1 09 47 PM" src="https://github.com/user-attachments/assets/1344c205-cefe-491c-8847-86b7c4adc54a">

**Comment by themerekat** [comment]
@Atticus29 there are definitely a lot of FR translations missing (not to mention Portuguese)! I think we just haven't gotten around to them, but good to note!
