### ISSUE TITLE
Merge exsiccatae function doesn't produce expected alerts

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1796]
When you click the **Merge exssicati** button, neither of the alerts expected by the code show up.
![image](https://github.com/user-attachments/assets/f7a6427e-831f-42fe-acfb-77f790ce1c82)

This happens in both the Development and the master branches
![image](https://github.com/user-attachments/assets/02c30853-39a2-4b00-8036-4a7f055b5cb4)

in collections/exsiccati/index.php

**Comment by MuchQuak** [comment]
In hotfix
