### ISSUE TITLE
Some target fields do not save to upload mapping profiles

### ISSUE THREAD

**Issue by ljwalker** [Symbiota/Symbiota#1819]
Specifically, this issue relates to the new materialSample and associatedOccurrence target fields available in the Data Upload Module. 

As observed in the Sandbox portal: 
- Top three target fields (in yellow) were mapped to _materialSample-preservationType_, _materialSample-remarks_, and _materialSample-sampleCondition_.
- Bottom target field (in yellow) was mapped to _associatedOccurrence:relationship_. 

![Screenshot 2024-10-29 at 11 37 49 AM](https://github.com/user-attachments/assets/9d8f42a7-3634-446e-814f-9482c03fe81f)

**Comment by ljwalker** [comment]
Perhaps this is a non-issue if the intention is to only use the Extended Data Uploader to import material sample and associations data?

**Comment by themerekat** [comment]
@ljwalker , I think this happens when the values cannot save due to special characters. I wonder if the dash in the mapped-to fields is preventing them from saving? Can you test with another field that has a dash in the field name?

**Comment by ljwalker** [comment]
Tested. Results: Remapping these source fields to target fields that don't contain dashes/special characters fixed the issue. _However_, I then re-tested by remapping and saving two other source fields to target fields that contain special characters (paleo-formation and specify:topo_quad), and those changes did save when I updated the import profile:
![Screenshot 2024-11-01 at 9 51 20 AM](https://github.com/user-attachments/assets/fac9d755-641c-4274-a959-23b739a927cf)

**Comment by NikitaSalikov** [comment]
There was an issue with the code that didn't display the mapping properly, however, it was decided to remove associatedOccurrences and MaterialSample entirely from Data Upload (Full Text Import) so that they could only be imported through Extended Data Import.
