### ISSUE TITLE
Ability to parse other catalog numbers from an import file (and put into omoccuridentifiers)

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1872]
## General description of development

Ability to better handle "other catalog numbers" (also called alternative identifiers) upon import. These now are stored in the omoccuridentifiers table when they are created through the occurrence editor, but if you import data, they are still stored in omoccurrences.otherCatalogNumbers. We want the importer to be able to bring the data into omoccuridentifiers instead.
- FULL TEXT UPLOADS: if there are already values in omoccuridentifiers for a specimen record, and the user has mapped a field in the incoming file to otherCatalogNumbers, we should dump the old values in omoccuridentifiers and load in the new ones.
- SKELETAL FILE UPLOADS: i

There are two other use cases that may be treated in this same project (see below).

## Community need / requesting party

USDA NA
CCH2 users (RSA)

## User story / use cases

1. A user has a spreadsheet with an "otherCatalogNumbers" field formatted like: "Tag name: Identifier; Tag name2: Identifier2". After importing, omoccurridentifiers should have 2 new rows, one for each tag name+identifier combo.
2. A user has a Darwin Core Archive that includes an alternative identifiers extension (https://rs.gbif.org/extension/gbif/1.0/identifier.xml) file. This should be parsed into the omoccuridentifiers table.
3. A user downloads a backup file and then wants to restore their database from that backup file. In the backup file should be an identifiers extension containing the contents of omoccuridentifiers, and that should be parsed nicely back into omoccurridentifiers when they Restore Backup File. Image below is from collprofiles.php when collid is not null.
![Image](https://github.com/user-attachments/assets/ced7a220-ee56-4d81-9703-e8213e977bd1)

## Database schema adjustments

We may need another temp table that can hold extended data imports.

## Dependencies

?

## Overall timeline

Slated for 3.2 release, but will likely be done by the end of November.

## Key notes & changes
- **11/13** - we discussed the possibility of excluding this from the main importer and adding it to the extended data importer. We nixed this because of user experiences wanting to import, e.g., old accession numbers and NPS numbers from collectors. We didn't want to overcomplicate the user experience.

**Comment by MuchQuak** [comment]
Was merge into development
