### ISSUE TITLE
[bug] When you use a bounding box to search, then return to your search criteria, the bounding box moves

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1908]
I conducted a search with these criteria (in CCH2):
![image](https://github.com/user-attachments/assets/7fa4fc55-9d3a-463f-a36a-d85ebd10e62f)

Then I hit Search Criteria to go back to my search:
![image](https://github.com/user-attachments/assets/fd1a3c50-f9d9-4cc8-a836-273be2fb9604)

And now my bounding box has moved into the ocean:
![image](https://github.com/user-attachments/assets/479a10c1-5247-4114-b1bc-3c777f627de6)

Oddly, this seems to be negating the latitude.

What I also noticed is that the longitude should be negative (because it's in the Western hemisphere), but it's not listed as negative. However, the longitude seems to stay the same. Is everything getting negated at once, so that the longitude actually displays correctly, and the latitude gets negated?

**Comment by themerekat** [comment]
The same thing happens when you chose the "point-radius" searching method.
![image](https://github.com/user-attachments/assets/1050c02b-c2d7-467e-899d-7e17c1785561)

It does NOT happen when you do a custom polygon.

**Comment by MuchQuak** [comment]
> The same thing happens when you chose the "point-radius" searching method. ![image](https://github.com/user-attachments/assets/1050c02b-c2d7-467e-899d-7e17c1785561)
> 
> It does NOT happen when you do a custom polygon.

It looks like this is because the direction selection is not being saved when going back to the search and the map is reading that for doing the negation calculations. I can get a fix up quick for it
