### ISSUE TITLE
Multiple return types for a function require PHP 8+ 

### ISSUE THREAD

**Issue by mickley** [Symbiota/Symbiota#1916]
In utilities/Symbutil.php, a compatibility function for mysqli_execute_query() is defined ([L10](https://github.com/BioKIC/Symbiota/blob/279ddd6e5f6e7ea496c5a92a6516b4df871a3b01/utilities/SymbUtil.php#L10)). However, the function definition uses multiple return (union) types (e.g., mysqli_result | bool). Multiple return types require PHP 8+, so this code does not work on PHP versions prior to PHP 8, which would seem to be the goal. 

@MuchQuak

**Comment by MuchQuak** [comment]
> In utilities/Symbutil.php, a compatibility function for mysqli_execute_query() is defined ([L10](https://github.com/BioKIC/Symbiota/blob/279ddd6e5f6e7ea496c5a92a6516b4df871a3b01/utilities/SymbUtil.php#L10)). However, the function definition uses multiple return (union) types (e.g., mysqli_result | bool). Multiple return types require PHP 8+, so this code does not work on PHP versions prior to PHP 8, which would seem to be the goal.
> 
> @MuchQuak

Thanks for catching that. I have a hotfix pr in review to get it corrected

**Comment by mickley** [comment]
@MuchQuak: Excellent, thank you!

**Comment by MuchQuak** [comment]
Closing issue, fix is group into the next hotfix rotation
