### ISSUE TITLE
When viewing results of a cross-portal search, change the title of the "Records" tab to "Internal Records" for clarity

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1942]
![image](https://github.com/user-attachments/assets/13a35237-e0e1-4ed2-8d50-d295f520b9c0)

**Comment by themerekat** [comment]
Also, Frank is wondering how feasible it would be to add the title of the portal from which the records are coming to the top of the records list, like so:
![image](https://github.com/user-attachments/assets/881351e5-262b-4ea7-ab17-2acf4f6a1d5b)

**Comment by MuchQuak** [comment]
> Also, Frank is wondering how feasible it would be to add the title of the portal from which the records are coming to the top of the records list, like so: ![image](https://private-user-images.githubusercontent.com/16688784/393903733-881351e5-262b-4ea7-ab17-2acf4f6a1d5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NzEyMzEsIm5iZiI6MTczMzc3MDkzMSwicGF0aCI6Ii8xNjY4ODc4NC8zOTM5MDM3MzMtODgxMzUxZTUtMjYyYi00ZWE3LWFiMTctMmFjZjRmNmExZDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDE5MDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYjNiNzNjZjA3MjNhOTRiYTMzZDZkMjk5MTc4ODcxYmY0Zjc2ZjgzMzNhMWY2MjZmODNhMGRlMDQ1N2UwMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c60EbCkBkk4giCVlg5vskpvivmihyySceU1BuSu1OQE)

Sounds reasonable I will investigate
