### ISSUE TITLE
In quick search, conduct an "Edit" search when the user hits "Enter" on their keyboard

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#1948]
Currently, when you hit "Enter" after putting something in a quick search field, nothing happens. A user indicates that they would like it to conduct an "Edit" search when they hit Enter. I think this would be widely appreciated.
![image](https://github.com/user-attachments/assets/099cdd6f-2043-43ee-a36b-99dd3a330b09)

**Comment by Atticus29** [comment]
@themerekat if a user doesn't have edit access to the collection, do you want enter to kick off the search instead or do nothing?

**Comment by themerekat** [comment]
@Atticus29 , oo, good question...I forgot that people without edit access can view. Yes, I think it should just kick off a normal search.

**Comment by Atticus29** [comment]
Fixed in https://github.com/BioKIC/Symbiota/pull/1951.
