### ISSUE TITLE
Paleo - Change the display layout in list view

### ISSUE THREAD

**Issue by NikitaSalikov** [Symbiota/Symbiota#1979]
![image](https://github.com/user-attachments/assets/16d82ae8-dd3e-4261-b0ec-3f4d3a46be58)

Additionally, for clarity, that row could begin with a header/prefix, "Geological Context:"
 
Kind of like:
Catalog Number...
Locality Information...
Geological Context: earlyInterval to lateInterval formation

**Comment by ljwalker** [comment]
Per forthcoming 3.2 release, sorting in List View is a new feature (compare this screenshot to the original one above).

Somewhat relates to the recent PR #2175 (see fix for listtabledisplay.php).

Screenshot from dev005: /paleo/collections/list.php
<img width="1005" alt="Image" src="https://github.com/user-attachments/assets/969a0d80-5240-4f0c-b0ac-f97fcc31b056" />

**Comment by NikitaSalikov** [comment]
@ljwalker Yes, I think it's a new one. I can add the geo context fields to sorting selector if required.
