### ISSUE TITLE
User email of Symbiota users

### ISSUE THREAD

**Issue by Kantoborgy** [Symbiota/Symbiota#243]
Hi all,
There is some way to prevent anyone from seeing the email of symbiota users, for example when executing the link https://...symbiotaportalx/portal/profile/userprofile.php?userid=2.    I have a spam problem on my e-accounts.

Thanks in advance

**Comment by Kantoborgy** [comment]
> Hi all, There is some way to prevent anyone from seeing the email of symbiota users, for example when executing the link https://...symbiotaportalx/portal/profile/userprofile.php?userid=2. I have a spam problem on my e-accounts.
> 
> Thanks in advance

**Comment by themerekat** [comment]
Fixed
