### ISSUE TITLE
All portals searched when only one portal is specified

### ISSUE THREAD

**Issue by jbest** [Symbiota/Symbiota#247]
When specifying which collections to search in a portal (e.g. https://portal.torcherbaria.org/portal/collections/index.php), I uncheck the check box for "Select/Deselect all collections" then select the one portal I want to search (e.g. TORCH). I click the search button then enter a scientific name or other parameters and press the List button. The results include records from all SEINet portals rather than just the one portal. When I return to the Search Collections page, the checkbox for "Select/Deselect all collections" is selected.

If I manually check individual collections within a portal (not the single portal checkbox) the search results only include those designated collections. I've tested this on TORCH and SERNEC portals with the same result. Tested on Chrome and Firefox on Windows and Mac.

**Comment by themerekat** [comment]
Confirmed this is still problematic in TORCH portal (likely all the others, too).

**Comment by ChrisGrinter** [comment]
This happens in a similar way in Monarch (we just updated BioKiC versions). When we select one or a few portals to search we correctly get that search results. Then when going back to the main page to add all portals (uncheck then re-check all), the recheck all button does not actually apply the search to all collections. You have to manually re-click every button to fully run the search. The Select/Deselect button seems to be broken.

**Comment by GregoryPost** [comment]
Tested deployed fix onTORCH and CCH2.
