### ISSUE TITLE
DwC archive refresh error 

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#311]
I went to refresh my DwC today on the Bee Library via
        UCSB Symbiota DwC-A import with BeeFilter (IPT Resource - #12) 
And received a series of warnings (image attached)
WARNING: meta.xml field order out of sync w/ occurrences.csv; remapping: field #41 => occurrenceRemarks

![Screen Shot 2022-10-11 at 12 56 13 PM](https://user-images.githubusercontent.com/16688784/195191487-8191e847-804c-4810-8196-9ed83d64ec2e.png)

**Comment by themerekat** [comment]
(From Katja Seltmann)

**Comment by GregoryPost** [comment]
Ed fixed with [8bdf509]
