### ISSUE TITLE
Symbiota RSS url changes

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#334]
From Dan S (iDigBio). Problem with Symbiota RSS url changes.

"The issue is that the "old" rss url continues to be served and returns HTTP status code 200, but is "empty".  Many Symbiota portal datasets in iDigBio are now out-of-date since we can't process any updates after the RSS url changes and until we notice the problem.  Since the old url is still a valid xml document, we don't currently have a good way to detect the issue.   Any other consumers of these RSS feeds may likely be having similar issues.  Can we get word to the software developers about this?  Basically, I request that the old RSS feed url that is typically served at /webservices/dwc/rss.xml be disabled / turned off / stop serving HTTP 200 when the new rss handler url is enabled.  Is an actual HTTP redirect possible?
At that point, we'll be able to see when the change happens and can update our registry of RSS urls to use the new feed location.

The xml document at the rss location contains:
```
<?xml version="1.0" encoding="UTF-8"?>
<redirect><newLocation>../../content/dwca/rss.xml</newLocation></redirect>
```
which is valid XML but not RSS.
When I started writing all this I was thinking the document was actually empty, rather than just empty of any RSS contents."

**Comment by danstoner** [comment]
Hi folks,

This "RSS redirect" was a new thing we hadn't seen before.   :flushed: A little research goes a long way and I see this style of xml with `<redirect>` tags does seem to be the way RSS feed urls are supposed to be moved if a HTTP 301 redirect is not possible.

Sorry for the confusion on our end.

**Comment by danstoner** [comment]
Feel free to close, no action requested.
