### ISSUE TITLE
Batch Determination tool not applying new determinations

### ISSUE THREAD

**Issue by mandrewj** [Symbiota/Symbiota#393]
When using the batch determination tool the new determination is not added to the occurrence. The page will retun a 'completed' message with no errors, but when you go to the specimen record(s) they do not have the determination.

This is happening in both Ecdysis and the NEON Biorepository portal - I did not yet test others.

It was first reported to me today (and then I confirmed on the 2 portals) - it looks like the page and the linked php classes have not been edited since January - so either it has been broken since at least then or perhaps something else happened on a related page?

The lack of an error might indicate that this has been going on unnoticed for a while.

**Comment by GregoryPost** [comment]
I believe this issue was addressed in #381

**Comment by themerekat** [comment]
@mandrewj  This has been fixed in the master code, but I don't know if it's been pushed to production everywhere.
