### ISSUE TITLE
[Dev branch] "More information" dropdown does not match portal styling

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#888]
/collections/misc/collprofiles.php?collid=1

![image](https://github.com/BioKIC/Symbiota/assets/16688784/8f710534-5bba-42ed-a9e0-123ec0818fd1)

I think this should be green, not blue.

**Comment by Atticus29** [comment]
This is a duplicate of https://github.com/orgs/BioKIC/projects/6/views/14?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status&pane=issue&itemId=49328785. I'm gonna mark that one as rejected in favor of this one, because this one has an associated github issue.

**Comment by Atticus29** [comment]
@NikitaSalikov if helpful, I believe that different css files are being used for the two different PHP files, which is at least part of - if not the entire - problem.

**Comment by themerekat** [comment]
Appears to have been fixed
