### ISSUE TITLE
[Dev-branch] Standardized minus (and sometimes plus) icon missing in collections/search/index.php and collections/misc/collstats.php

### ISSUE THREAD

**Issue by Atticus29** [Symbiota/Symbiota#897]
<img width="1552" alt="Screen Shot 2024-01-30 at 4 47 57 PM" src="https://github.com/BioKIC/Symbiota/assets/2775448/d27626b7-ca91-4dd7-92ee-d39786046557">

<img width="1552" alt="Screen Shot 2024-01-30 at 4 47 43 PM" src="https://github.com/BioKIC/Symbiota/assets/2775448/63f5941a-1903-4595-a4cd-e1334f8ec177">

If helpful, in the case of collections/search/index.php, the file calling plus.png and minus.png is called collections/search/singleCollectionGroupDetails.php.

In the case of collstats, I think the file is just collections/misc/collstats.php.

After those icons have been implemented, hand off to @Atticus29 , who will get the button click and icon hiding/showing working as desired.

**Comment by themerekat** [comment]
@Atticus29 , hmmm it looks correct on my localhost. I have the dev branch checked out
![image](https://github.com/BioKIC/Symbiota/assets/16688784/0ad27fdf-5882-4d8a-8b81-819ee6646fb7)

and

![image](https://github.com/BioKIC/Symbiota/assets/16688784/e28c050e-ae49-477d-88a9-84a49f73a0a5)

**Comment by Atticus29** [comment]
@themerekat closing this. I can no longer reproduce in uswds-harlan-changes, Development, nor master.
