### ISSUE TITLE
[Dev-branch] Make improvements to new search page

### ISSUE THREAD

**Issue by Atticus29** [Symbiota/Symbiota#915]
# Items to change/fix/implement

- Default all accordions to closed except for taxonomy

- Add trait search section (has config in symbini file, allows you to designate which traits are searchable)

- Add expand all button

- Rearrange the accordions:

- Final order should be
    - Taxonomy
    - Location
    - Collector
    - Specimen Criteria
    - Trait
    - Collection

- Add material sample search section

# Other aspects worth considering

- How challenging is it to add: “Limit to specimens with associated occurrences”?
-  And material
- Thing to mentally bookmark for when you get to working on the search form: The GEO OSE (paleo) grant included funds to include some fields from the Paleo Module on the search form. Definitely not something to worry about for now, but just FYI
- Under collections - can we ditch the logos and clean up how they appear?  Like crazy idea, can it just be a drop down pick list (ditching the check boxes entirely). 
    - We’d have to be mindful of users to who want to search more than one collection, though. Some sort of multi-dropdown with chips (not unlike what we have in the “criteria” section already (see screenshot) might be a good solution to this.
As I think about this more, we also have to consider what to do about users who want to select entire categories of collections as well (e.g., all algae collections or all bryophyte collections only). Can’t think of a less clunky way to implement that right now.

**Comment by Atticus29** [comment]
[PR](https://github.com/BioKIC/Symbiota/pull/981) for the first part of this.

**Comment by Atticus29** [comment]
@themerekat all of these are done except 
> Under collections - can we ditch the logos and clean up how they appear? Like crazy idea, can it just be a drop down pick list (ditching the check boxes entirely).

Not sure whether to close this issue or not...

**Comment by themerekat** [comment]
I vote we can close it; this is more of a revamp idea.
