### ISSUE TITLE
[Dev-branch] Cross-portal searching tool feedback

### ISSUE THREAD

**Issue by themerekat** [Symbiota/Symbiota#974]
This is a thread to capture feedback for the cross-portal searching capabilities. Please comment with your feedback below, and it will be discussed or addressed.

**Comment by themerekat** [comment]
Some feedback:

- This will only show things that are mappable
- Can only search one other portal at a time

**Comment by harringtonah** [comment]
I did a polygon-constrained search but left the other fields blank- this led to a "null search" error that I struggled to escape (will reload the page shortly). Text of error, which was repeated across the page where the map previously displayed: "502
Deprecated
: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in
/var/www/html/sandbox/dev/classes/OccurrenceMapManager.php
on line "

**Comment by jrallen99** [comment]
![image](https://github.com/BioKIC/Symbiota/assets/95655326/2eab53f4-278e-425b-901f-f9d1b13c12b8)


I received this error trying to download a csv file

**Comment by jrallen99** [comment]
Seems if the search times out or ends up with an error that you cannot recover the page you were working on. I had to refresh/restart the page to get it unstuck.

**Comment by jrallen99** [comment]
I hate the idea of centroids for county and state info, but if this is limited to specimens with coordinates, is there a way to run the geographic search and then a text based search or a reverse lookup to find records from a county based on the placement of the polygon? I know this would get tricky logistically with polygons because they would not occupy an entire county so you would get more than you ask for.

**Comment by STHerbariumLSU** [comment]
Ecologist would likely want to extend this search beyond two distinct taxon groups.  Thus, the external portal may need to multiple.  In this case, it would be nice to have the results merged.  Even searching two portals at once would benefit from merging the data output into a single spreadsheet.  But this is a great start to look at biocrusts!

**Comment by STHerbariumLSU** [comment]
How would one do a general search for associate species?  I would be nice to type in a scientific name and a distance from these occurence records to see what else pops up.  This is probably not easy to program!

**Comment by themerekat** [comment]
> How would one do a general search for associate species? I would be nice to type in a scientific name and a distance from these occurence records to see what else pops up. This is probably not easy to program!

@STHerbariumLSU , you could just include one taxon and then use a circle/radius search!

**Comment by STHerbariumLSU** [comment]
Is there a way to add a map layer for county boarders?  I find these really useful for may applications.

**Comment by themerekat** [comment]
> Is there a way to add a map layer for county boarders? I find these really useful for may applications.

I don't think there is one naturally included in any of the leaflet layers, oddly enough. That probably warrants a feature request for the whole code: https://github.com/BioKIC/symbiota-docs/issues/465

**Comment by themerekat** [comment]
> How would one do a general search for associate species? I would be nice to type in a scientific name and a distance from these occurence records to see what else pops up. This is probably not easy to program!

@STHerbariumLSU , I think you could do a search for one taxon in the main portal, and then a search for a large taxon like "Plantae" in the other portal.

Have you tried entering a taxon in the first Taxon field, but not the second?

**Comment by blankaaguero** [comment]
I did a random search of Pinus arizonica above, Pinus aristata in cross portal. The points of both species on the map have the same color. I'd like to see them in different colors. When mousing over the points, I see collector & number, but not which one of the two taxa the point belongs to.

**Comment by themerekat** [comment]
> I did a random search of Pinus arizonica above, Pinus aristata in cross portal. The points of both species on the map have the same color. I'd like to see them in different colors. When mousing over the points, I see collector & number, but not which one of the two taxa the point belongs to.

Hi @blankaaguero , you can do this by navigating to the Taxa List tab and clicking the Auto Color button (or you can manually change the color by clicking a color box)
![image](https://github.com/BioKIC/Symbiota/assets/16688784/c25a34fb-55ea-4369-8a0a-f9b706b59bcc)

**Comment by blankaaguero** [comment]
Right, I see how it works, thanks. Would it be possible to get the first display in 2 colors, separating the two searches graphically on the map?

**Comment by themerekat** [comment]
> Right, I see how it works, thanks. Would it be possible to get the first display in 2 colors, separating the two searches graphically on the map?

Probably! That does seem more intuitive.

**Comment by STHerbariumLSU** [comment]
The Detailed Specimen Record pops up with the full resolution image for TEX.  It would fit best on the screen by opening first with a thumbnail that be further explored to show more resolution as needed.

**Comment by STHerbariumLSU** [comment]
About the color mapping....I think that it would be nice to have the default be autocolor.  I was also a bit confused at first by the monochromatic points on a map.  Also, the colors are by collection and shapes are observation/collection.  Could there be another layer (maybe cross-hatching) that shows from which portal the records are pulled?

**Comment by STHerbariumLSU** [comment]
> > How would one do a general search for associate species? I would be nice to type in a scientific name and a distance from these occurence records to see what else pops up. This is probably not easy to program!
> 
> @STHerbariumLSU , I think you could do a search for one taxon in the main portal, and then a search for a large taxon like "Plantae" in the other portal.
> 
> Have you tried entering a taxon in the first Taxon field, but not the second?

Ah, I created a circle-delimited area and was able to search all records in the primary portal for that area (leaving "taxon" null).  Results were all plant records.  Then, I checked the box for "cross-portal" searches and "taxon" null.  This returned reptiles in this region, along with the plants.  NICE!!  Error free results as far as I know.  I get mixed results when typing in specific taxa into the different portals.  See errors below...

**Comment by STHerbariumLSU** [comment]
<img width="527" alt="Screen Shot 2024-03-02 at 8 17 33 AM" src="https://github.com/BioKIC/Symbiota/assets/74327117/34130609-80f5-44bc-a4d1-d4b003b8f3ae">
Probably mentioned before but here it is again:
If a taxon doesn’t exist, the program doesn’t stop searching.  Or doesn’t time out quickly enough.  Got the spinning wheel with search of Briza maxima and Briza minor.  The primary portal returns a null search, but the external portal is slow or doesn’t time out when the answer is “null”.

**Comment by STHerbariumLSU** [comment]
Searched Locality “Big Bend” and a few insect collections popped up.  However, the map disappeared quickly.  I tried this again and found that the only records returned (at first) were in China (missing "-" on longitude).  Then, many moments later, the map populated records from all over the USA where "big bend" was found in the text string.  So, it might be nice to show a spinning wheel or something that notes the search still in progress.  I was a large query!

**Comment by STHerbariumLSU** [comment]
Here's a common error msg when a specific record doesn't return full results:
<img width="1107" alt="Screen Shot 2024-03-05 at 7 33 12 PM" src="https://github.com/BioKIC/Symbiota/assets/74327117/67dcef1f-0b00-466a-97f6-33bb96429e8e">

**Comment by STHerbariumLSU** [comment]
At one point the checkbox of “cross portal search” was visible, but “Logan’s test portal” and the “taxon” field was not.  I’m not certain how I created this.  Sorry no screenshot!

**Comment by STHerbariumLSU** [comment]
I conducted a search for “Asteraceae” within a designated square and returned many records.  Separately, in the same square, I returned 3 records for “Coleoptera” (beetles).  However, When I combined the searches, either errors were produced, or the map only included a single record of Asteraceae (Echinacea sanguinea, Allen #9088) combined with the 3 Coleoptera. 
<img width="885" alt="Screen Shot 2024-03-11 at 10 25 25 AM" src="https://github.com/BioKIC/Symbiota/assets/74327117/b9f88742-793d-47d2-8240-539f331548dd">

**Comment by STHerbariumLSU** [comment]
The map won’t visibly clear records when pressing “reset” near the “search” button but a new search is allowed. “Delete selected shape” does work as expected!

**Comment by STHerbariumLSU** [comment]
It took a moment to learn that the record list/spreadsheet is responsive on the map.  I wonder if there is a way to post a note about this at the top of the list, such as “click to see on map”.  I really liked how it zoomed right into an area.  It might be nice to take this further and have the point "light up" on the map when referenced from the list.

**Comment by STHerbariumLSU** [comment]
When dropping a shape, click and drag requires a certain map resolution.  This is fine, but it would be nice to be able to modify the shape after dropping it, such as widen, move left, etc.

**Comment by STHerbariumLSU** [comment]
I conducted a search of a Louisiana parish, Saint Tammany, with taxon null.  It returned 5 records for the primary portal and 3 for the external portal.  However, the map only shows 5 records when zoomed in. It shows 8 when zoomed out with clustering.  I couldn’t see the details of all these records and am not sure if georeferencing effects results.  Following this search further, I created a new search using only a shape delimitation and found over 500 records for the area.  And, a third cross-portal search for “saint tammany” returned 49 records.  Not sure what’s happening here. 
<img width="1289" alt="Screen Shot 2024-03-11 at 10 54 06 AM" src="https://github.com/BioKIC/Symbiota/assets/74327117/5b5581a2-9dfe-4faa-af78-2d1c87e99fc1">
<img width="1193" alt="Screen Shot 2024-03-11 at 10 55 11 AM" src="https://github.com/BioKIC/Symbiota/assets/74327117/0b326052-645c-4d76-baf7-f102db5d4f19">
<img width="1241" alt="Screen Shot 2024-03-11 at 10 57 10 AM" src="https://github.com/BioKIC/Symbiota/assets/74327117/37978b0e-b08c-4811-bac9-5ffa4b89fe90">

**Comment by blankaaguero** [comment]
The error "Fatal error: Uncaught Error: Cannot use string offset as an array in /var/www/html/wilt/portal/classes/OccurrenceIndividual.php:315 Stack trace: #0 /var/www/html/wilt/portal/classes/OccurrenceIndividual.php(172): OccurrenceIndividual->setAdditionalIdentifiers() #1 /var/www/html/wilt/portal/collections/individual/index.php(31): OccurrenceIndividual->setOccurData() #2 {main} thrown in /var/www/html/wilt/portal/classes/OccurrenceIndividual.php on line 315"
only happens to me when I want to see details of returned records from the "External Records" Tab (clicking on they hyperlink of collector+col.number). If I do that on the "Records" tab, it shows details without error.

Well, there's an error for some searches even in the Records tab. I looked like ASU collections with catalog# filled in work, but the link worked only for the first one of the 2 specimens from ASU (searched Taraxacum above, Poa annua in cross-portal).

**Comment by blankaaguero** [comment]
The "Copy URL to clipboard" button on the "Results" tab copies a link to clipboard (https://biokic4.rc.asu.edu/sandbox/dev/collections/map/index.php?undefined) but it doesn't lead to any data. Shouldn't it contain the SQL syntax of the search = when I paste it to a new browser window, I'd expect to get a map with those specimens in the "Results" tab. Right?

**Comment by blankaaguero** [comment]
The KML file download button worked. When I opened the downloaded kml  file in Google Earth, it opened it in the middle of Pacific. The points were there, but whenever I clicked on that set of points, the view turned to the middle of Pacific.
KML file downloaded from "External Records" worked well, and focused the map over the Southwest, not over the Pacific.
(I searched Taraxacum above, and Poa annua below in Logan's test portal.)

**Comment by themerekat** [comment]
> The "Copy URL to clipboard" button on the "Results" tab copies a link to clipboard (https://biokic4.rc.asu.edu/sandbox/dev/collections/map/index.php?undefined) but it doesn't lead to any data. Shouldn't it contain the SQL syntax of the search = when I paste it to a new browser window, I'd expect to get a map with those specimens in the "Results" tab. Right?

Yep, the link should definitely take you somewhere!

**Comment by blankaaguero** [comment]
Tab "Records" and tab "External Records" both: clicked first button "download the data": it opened a symbiota window for downloading backups, I left the default values, and in both cases got an error: Fatal error: Uncaught mysqli_sql_exception: Unknown column 'o.vitality' in 'field list' in /var/www/html/sandbox/dev/classes/DwcArchiverCore.php:1639 Stack trace: #0 /var/www/html/sandbox/dev/classes/DwcArchiverCore.php(1639): mysqli->query('SELECT DISTINCT...', 1) #1 /var/www/html/sandbox/dev/classes/DwcArchiverCore.php(842): DwcArchiverCore->writeOccurrenceFile() #2 /var/www/html/sandbox/dev/collections/download/downloadhandler.php(185): DwcArchiverCore->createDwcArchive() #3 {main} thrown in /var/www/html/sandbox/dev/classes/DwcArchiverCore.php on line 1639

**Comment by blankaaguero** [comment]
I clicked on the Home link in the upper right search box space, it opened Symbiota home page. I clicked Back arrow, and returned to the search window. It opened this view below, that was missing the second species search window. When I unselected the "Enable to cross portal search" and selected it again, the second species search window appeared.
![Clipboard01](https://github.com/BioKIC/Symbiota/assets/14986113/74f493bf-bc29-4925-90de-bacdbea84148)

**Comment by themerekat** [comment]
> Tab "Records" and tab "External Records" both: clicked first button "download the data": it opened a symbiota window for downloading backups, I left the default values, and in both cases got an error: Fatal error: Uncaught mysqli_sql_exception: Unknown column 'o.vitality' in 'field list' in /var/www/html/sandbox/dev/classes/DwcArchiverCore.php:1639 Stack trace: #0 /var/www/html/sandbox/dev/classes/DwcArchiverCore.php(1639): mysqli->query('SELECT DISTINCT...', 1) #1 /var/www/html/sandbox/dev/classes/DwcArchiverCore.php(842): DwcArchiverCore->writeOccurrenceFile() #2 /var/www/html/sandbox/dev/collections/download/downloadhandler.php(185): DwcArchiverCore->createDwcArchive() #3 {main} thrown in /var/www/html/sandbox/dev/classes/DwcArchiverCore.php on line 1639

Hm, looks like a portal configuration problem, not a cross-portal searching tool problem. I'll touch base with the devs.

**Comment by themerekat** [comment]
> I conducted a search of a Louisiana parish, Saint Tammany, with taxon null. It returned 5 records for the primary portal and 3 for the external portal. However, the map only shows 5 records when zoomed in. It shows 8 when zoomed out with clustering. I couldn’t see the details of all these records and am not sure if georeferencing effects results. Following this search further, I created a new search using only a shape delimitation and found over 500 records for the area. And, a third cross-portal search for “saint tammany” returned 49 records. Not sure what’s happening here. <img alt="Screen Shot 2024-03-11 at 10 54 06 AM" width="1289" src="https://private-user-images.githubusercontent.com/74327117/311775303-5b5581a2-9dfe-4faa-af78-2d1c87e99fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjI0MjEsIm5iZiI6MTcxMDI2MjEyMSwicGF0aCI6Ii83NDMyNzExNy8zMTE3NzUzMDMtNWI1NTgxYTItOWRmZS00ZmFhLWFmNzgtMmQxYzg3ZTk5ZmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE2NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZmJiYTBmODA1NWEyOWFkN2Y0YWMzYTE2NTg0OTdiZWQ1Mzk5NDIxYjNiNzY1M2M4MGY1M2M5MDc2YTViMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FscRb39Oy0auJ0uhUMi87kKNXSPcqNfgrykM0F7ylGY"> <img alt="Screen Shot 2024-03-11 at 10 55 11 AM" width="1193" src="https://private-user-images.githubusercontent.com/74327117/311775349-0b326052-645c-4d76-baf7-f102db5d4f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjI0MjEsIm5iZiI6MTcxMDI2MjEyMSwicGF0aCI6Ii83NDMyNzExNy8zMTE3NzUzNDktMGIzMjYwNTItNjQ1Yy00ZDc2LWJhZjctZjEwMmRiNWQ0ZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE2NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMzkzYmI4MDMwMWI2YzE1NmJhZDMyNzY5NmZhNDNjM2FmMTgxNTFmNmY1MzViMWRkNDYyNTQxMjZhYjRmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cX9o3j_sI9FI6LTIKH1H2mUesPAn1YEQcacGAF8XTG0"> <img alt="Screen Shot 2024-03-11 at 10 57 10 AM" width="1241" src="https://private-user-images.githubusercontent.com/74327117/311775382-37978b0e-b08c-4811-bac9-5ffa4b89fe90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjI0MjEsIm5iZiI6MTcxMDI2MjEyMSwicGF0aCI6Ii83NDMyNzExNy8zMTE3NzUzODItMzc5NzhiMGUtYjA4Yy00ODExLWJhYzktNWZmYTRiODlmZTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE2NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNTc0NTUxNzFiOGRiN2ZkMGY1N2IzYWRiNWVlNGE3MjljZmM5NzFkMmMyNWMzYzU3NzljODgzNzU1Yjc0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q6VTQslIDHGbUYRqbLaFa3xWyzh_7WFzKEYtSTLRjQo">

I think the problem you are experiencing here is one of data standards: the portal preferred name for this parish is "St. Tammany" rather than "Saint Tammany"

**Comment by themerekat** [comment]
Summary of checkpoint meeting feedback:
**Things to change**:
- ~~Autocolor by default instead of leaving the same color~~
- ~~Option to autocolor (or texture?) by portal of origin~~
- ~~If a taxon doesn't exist in one of the portals, give error message instead of loading forever~~
- ~~Visibly clear records from the map when pressing “reset” near the “search” button~~
- ~~Indicate that clicking on the table view will take you to that point on the map ("click to Zoom to record and view details" or something like that). Tooltip.~~
- ~~The "Copy URL to clipboard" button on the "Results" tab copies a link to clipboard, but the link is broken/unusable~~
- ~~If you cross-portal search, then click Home, then return to map search, "Enable Cross Portal Search" will remain checked, but the dropdown list of portals to search & the Taxa Search field disappear. Happens when you click the back button in the browser.~~
- Search cache seems not to clear every time because search results are different between searches? [KATIE NEEDS TO RESEARCH THIS ONE MORE]

**Remaining questions**:
- How to deal with the fact that you cannot cross-portal search for things that are not georeferenced? (make a note?)
- Can county borders be included in map options?
- Are there plans to be able to search more than 2 portals _at a time_? (needs more discussion)

**To Do**:
- [x] Move testing environment to a different server --> actually solve the problem with being able to open records in Logan's Test Portal (external source)
- [ ] Get info about what datasets are in Logan's Test Portal

**Comment by themerekat** [comment]
When you click the Reset button, it resets the search variables for the portal you are currently in, but not the search variables for the _other_ portal you are searching in
![image](https://github.com/BioKIC/Symbiota/assets/16688784/95dfbee9-f7d6-4189-a20c-0ceea554a74a)

**Comment by themerekat** [comment]
Weird behavior when you cross-portal search and then revert back to single-portal search. Results will initially be the same as your cross-portal search (show external records table), but then you won't be able to navigate back to that table after navigating to your current portal's search results.

**Comment by STHerbariumLSU** [comment]
I'm having so much fun with the mapping!  The colors are great in records tab.  Can the Portal List and Collections List also default to "auto color"?    - Aaah, probably ignore this....I think that they have to default to the plain colors so that the first display is the taxon name records.

**Comment by STHerbariumLSU** [comment]
When clicking on "see map point" in the records tab, can we zoom in more?  If there are lots of points in the region, it's impossible to sort out the selected point.  If we cannot zoom in more, maybe it can highlight somehow?

**Comment by STHerbariumLSU** [comment]
I'm finding that some of the mapped records have no taxon name.  Is it possible to add a checkbox to the search criteria, such as "Limit to records with sci name".  This would remove sci name = null and sci name = undetermined.

**Comment by STHerbariumLSU** [comment]
The Map Options have a few strange things...After a search is returned, if I unselect "turn off clustering", the records all disappear.  There are similar issues with toggling between heat map that I'll discuss in the next comment....

**Comment by STHerbariumLSU** [comment]
In Map Options, selecting "heat map" displays both records and the heat map.  If you toggle this field, subsequent maps are heat map only or record points only.  It's nice to have all three options: both, heat map only, and point map only.

**Comment by STHerbariumLSU** [comment]
Not sure why the taxon names are parsed so much.  It seems that the list should have only two families for all the penstemon species listed.
<img width="1173" alt="Screen Shot 2024-04-10 at 11 19 14 AM" src="https://github.com/BioKIC/Symbiota/assets/74327117/326a723f-7a3b-422a-ae03-55ecdf50db76">

**Comment by STHerbariumLSU** [comment]
Also not sure why the full sci name doesn't show up in the record details, when it's listed in the records list and comes up in the search correctly.
<img width="1415" alt="Screen Shot 2024-04-10 at 11 03 08 AM" src="https://github.com/BioKIC/Symbiota/assets/74327117/f0d1682a-cbeb-4c8c-b5fe-7dc06ef26be4">

**Comment by themerekat** [comment]
> Not sure why the taxon names are parsed so much. It seems that the list should have only two families for all the penstemon species listed. <img alt="Screen Shot 2024-04-10 at 11 19 14 AM" width="1173" src="https://private-user-images.githubusercontent.com/74327117/321327913-326a723f-7a3b-422a-ae03-55ecdf50db76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzIzMzEsIm5iZiI6MTcxMjc3MjAzMSwicGF0aCI6Ii83NDMyNzExNy8zMjEzMjc5MTMtMzI2YTcyM2YtN2EzYi00MjJhLWFlMDMtNTVlY2RmNTBkYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE4MDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Y2UxODkxYzM4YjJkZDBlNWMxOTc4MDBkMDM5N2E2N2RlNmE3MzVmYThmZjY4ZTllNzNiZGQ1MDQzODkzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.12AqHcYsdyLIrC8KehFz-_vYWP8hcc-fGopBjPuYuus">

This is probably a problem with the data, not the tool

**Comment by themerekat** [comment]
When you conduct a cross-portal search, External Record results only show specific epithet

![image](https://github.com/BioKIC/Symbiota/assets/16688784/7cc70213-5d10-4cd7-ae7e-be482bfe512f)

![image](https://github.com/BioKIC/Symbiota/assets/16688784/30dad7af-ab4c-4ff3-80f1-ea735d8cf54b)

![image](https://github.com/BioKIC/Symbiota/assets/16688784/041ee7a9-0c7a-4d19-b6e0-fa936fb3d5fa)

**Might just be a problem with the test dataset / portal**

**Comment by themerekat** [comment]
> Not sure why the taxon names are parsed so much. It seems that the list should have only two families for all the penstemon species listed. <img alt="Screen Shot 2024-04-10 at 11 19 14 AM" width="1173" src="https://private-user-images.githubusercontent.com/74327117/321327913-326a723f-7a3b-422a-ae03-55ecdf50db76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzIzMzEsIm5iZiI6MTcxMjc3MjAzMSwicGF0aCI6Ii83NDMyNzExNy8zMjEzMjc5MTMtMzI2YTcyM2YtN2EzYi00MjJhLWFlMDMtNTVlY2RmNTBkYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE4MDAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Y2UxODkxYzM4YjJkZDBlNWMxOTc4MDBkMDM5N2E2N2RlNmE3MzVmYThmZjY4ZTllNzNiZGQ1MDQzODkzYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.12AqHcYsdyLIrC8KehFz-_vYWP8hcc-fGopBjPuYuus">

**Problem:** the families are separated per portal even if the families are the same across portals.

**Possible solutions:** Either combine the lists, or separate the lists by portal (clearly with headers)

**Comment by themerekat** [comment]
> I'm finding that some of the mapped records have no taxon name. Is it possible to add a checkbox to the search criteria, such as "Limit to records with sci name". This would remove sci name = null and sci name = undetermined.

Talked about this. Potential enhancements.

**Comment by themerekat** [comment]
> The Map Options have a few strange things...After a search is returned, if I unselect "turn off clustering", the records all disappear. There are similar issues with toggling between heat map that I'll discuss in the next comment....

Current functionality:
Initial search: heatmap and points
Toggle off: points ONLY
Toggle on: heatmap ONLY

**Comment by themerekat** [comment]
> The Map Options have a few strange things...After a search is returned, if I unselect "turn off clustering", the records all disappear. There are similar issues with toggling between heat map that I'll discuss in the next comment....

If you do a search with clustering on, it's fine. But the toggle removes the points.
Search with clustering off, it's fine, too.

**Comment by themerekat** [comment]
Downloading records does not work (config issue?) but KML does

--> config problem, most likely

**Comment by themerekat** [comment]
When you click a number on the search results to go to the next page of External Records, the External Records tab turns into the Records (internal records) tab. You don't go to the next page of External Records.

**Comment by themerekat** [comment]
When you try to download the External Records, it does a download for the current portal instead of the external portal
![image](https://github.com/BioKIC/Symbiota/assets/16688784/8b8b5327-1f90-4878-a938-b1ddff3fdf41)
